
/* CodeQuest · Primer prototipo educativo. Sin servicios externos ni cuenta infantil. */
'use strict';
const STORAGE='codequest-v1';
const WORLDS=[
 {id:'inicio',title:'Mundo 1 · La chispa',subtitle:'Descubre cómo piensa un programa',color:'#336474',emoji:'⚡',level:'Aprendiz',lessons:['w1a','w1b','w1c']},
 {id:'constructor',title:'Mundo 2 · Constructor',subtitle:'Da vida a los objetos de Roblox',color:'#594587',emoji:'🏗️',level:'Constructor',lessons:['w2a','w2b','w2c']},
 {id:'inventor',title:'Mundo 3 · Inventor',subtitle:'Diseña tus propias mecánicas',color:'#73503f',emoji:'🚀',level:'Inventor',lessons:['w3a','w3b','w3c']}
];
const MISSIONS=[
 {id:'d1',world:'diagnostico',title:'El puente imposible',sub:'Construye y experimenta',time:8,emoji:'🌉',description:'¿Qué recuerdas de Roblox Studio? Crea cinco plataformas suspendidas, a diferentes alturas, y comprueba si tu personaje puede saltar entre ellas.',concept:'En Roblox Studio, las Parts se pueden mover, escalar y anclar. La propiedad Anchored evita que la física las haga caer.',code:'',question:'¿Qué propiedad evita que una plataforma caiga por la gravedad?',options:['Anchored','Transparency','Color'],answer:0,explanation:'Anchored mantiene la pieza fija en el mundo. No significa que esté oculta.',task:'Abre Roblox Studio, crea las cinco plataformas y pulsa Play. Cambia Anchored en una de ellas para ver qué sucede.',hints:['Busca las propiedades de la pieza seleccionada.','El nombre en inglés significa «anclado».','Activa Anchored para que una plataforma permanezca suspendida.'],reflection:'¿Qué has construido? ¿Qué ocurrió al probarlo?'},
 {id:'d2',world:'diagnostico',title:'El código misterioso',sub:'Descifra las instrucciones',time:8,emoji:'🔎',description:'Un programa usa palabras y símbolos para darle instrucciones al ordenador. No hace falta que sepas escribirlo todavía: intenta comprenderlo.',concept:'Una variable guarda un valor. El signo = asigna un valor; print lo muestra en la salida.',code:'local puntos = 0\npuntos = puntos + 1\nprint(puntos)',question:'¿Qué número muestra este código?',options:['0','1','2'],answer:1,explanation:'Empieza en cero, suma uno y después print muestra 1. Puedes probarlo en un Script.',task:'Explica en voz alta qué crees que sucede en cada línea. Si sabes usar un Script, prueba a ejecutarlo.',hints:['Busca dónde empieza el valor de puntos.','La segunda línea suma una unidad.','El resultado final es 1.'],reflection:'¿Qué línea entendiste mejor? ¿Cuál te resultó más extraña?'},
 {id:'d3',world:'diagnostico',title:'El error oculto',sub:'Investiga como un detective',time:8,emoji:'🛠️',description:'Queremos que una plataforma desaparezca y que el jugador pueda atravesarla. Alguien ha escrito este fragmento, pero olvidó algo.',concept:'Transparency cambia la visibilidad. CanCollide controla si el jugador choca con el objeto.',code:'local plataforma = script.Parent\nplataforma.Transparency = 1\nplataforma.CanCollide = true',question:'La plataforma es invisible pero el personaje sigue chocando. ¿Qué cambiarías?',options:['Transparency a 0','CanCollide a false','El nombre de la variable'],answer:1,explanation:'Aunque una parte sea invisible puede seguir teniendo colisión. Con CanCollide = false deja pasar.',task:'Sin copiar una solución completa, explica la causa del fallo. Si puedes, modifica una propiedad y comprueba el resultado.',hints:['Que no se vea no significa que no exista.','Investiga qué quiere decir collision.','La propiedad CanCollide debe estar en false.'],reflection:'¿Qué intentaste antes de saber la respuesta?'},
 {id:'w1a',world:'inicio',title:'La caja de los puntos',sub:'Variables y números',time:15,emoji:'💎',description:'Vas a crear una variable que guarde los puntos de un jugador.',concept:'local crea una variable local. Las variables guardan datos que pueden cambiar a medida que transcurre el juego.',code:'local puntos = 5\npuntos = puntos + 3\nprint(puntos)',question:'Si el jugador empieza con 5 puntos y gana 3, ¿qué aparece en Output?',options:['53','8','3'],answer:1,explanation:'Se suman los valores numéricos: 5 + 3 = 8.',task:'En Roblox Studio, escribe tú mismo un Script con una variable monedas. Empieza con 10, añade 2 e imprime el resultado. No copies este ejemplo: transfórmalo.',hints:['Crea una variable usando local.','Primero guarda 10 en monedas; después utiliza monedas = monedas + 2.','Para ver su valor usa print(monedas).'],reflection:'¿Para qué podrías utilizar variables en el juego que tienes en mente?'},
 {id:'w1b',world:'inicio',title:'La puerta del sí o no',sub:'Condiciones',time:15,emoji:'🚪',description:'Un videojuego decide qué hacer en función de una condición.',concept:'if comprueba una condición. Si es verdadera, ejecuta el código hasta end.',code:'local llaves = 2\nif llaves >= 2 then\n    print("Puerta abierta")\nend',question:'¿Qué pasa si cambiamos llaves = 2 por llaves = 1?',options:['Muestra puerta abierta','No muestra el mensaje','Da dos llaves nuevas'],answer:1,explanation:'Uno no es mayor ni igual que dos. El bloque del if no se ejecuta.',task:'Crea una condición que abra una puerta solo cuando monedas sea mayor o igual a 5. Prueba valores distintos.',hints:['La comparación es >=.','Escribe if monedas >= 5 then.','Recuerda cerrar el bloque con end.'],reflection:'¿Qué otro requisito pondrías para abrir una puerta especial?'},
 {id:'w1c',world:'inicio',title:'El reloj de las misiones',sub:'Tiempo y secuencias',time:15,emoji:'⏱️',description:'Controla cuándo suceden las cosas dentro de un videojuego.',concept:'task.wait(n) hace que un script espere aproximadamente n segundos antes de continuar.',code:'print("Preparados")\ntask.wait(2)\nprint("¡Ya!")',question:'¿Qué sucede entre los dos mensajes?',options:['Una espera de unos 2 segundos','Se borra el primer mensaje','El juego se cierra'],answer:0,explanation:'task.wait(2) crea una pausa de unos dos segundos.',task:'Crea una cuenta atrás de 3, 2, 1. Escribe los mensajes y añade una espera entre cada uno.',hints:['Primero imprime 3.','Después escribe task.wait(1).','Repite la secuencia con 2, 1 y el mensaje ¡Ya!'],reflection:'¿En qué parte de un videojuego sería útil una cuenta atrás?'},
 {id:'w2a',world:'constructor',title:'Plataformas invisibles',sub:'Propiedades de objetos',time:17,emoji:'👻',description:'Los objetos tienen propiedades que cambian su comportamiento.',concept:'Transparency usa valores de 0 (visible) a 1 (invisible); CanCollide activa o desactiva las colisiones.',code:'local parte = script.Parent\nparte.Transparency = 0.5\nparte.CanCollide = false',question:'¿Qué ocurre con la parte?',options:['Es semitransparente y atravesable','Es completamente visible y sólida','Desaparece del proyecto'],answer:0,explanation:'Transparency = 0.5 la hace semitransparente y CanCollide = false quita la colisión.',task:'Construye un camino secreto con tres plataformas. Haz que una sea semitransparente y que otra se pueda atravesar.',hints:['Empieza con una Part anclada.','Prueba valores como 0, 0.5 y 1 en Transparency.','CanCollide = false permite pasar a través.'],reflection:'¿Cómo avisarías al jugador de que existe un camino secreto?'},
 {id:'w2b',world:'constructor',title:'La plataforma sensible',sub:'Eventos',time:18,emoji:'🦶',description:'Un evento permite responder cuando algo sucede en el mundo del juego.',concept:'Touched se dispara cuando otra pieza entra en contacto con una Part. Connect vincula el evento con una función.',code:'local plataforma = script.Parent\nplataforma.Touched:Connect(function(otraParte)\n    print("¡Algo tocó la plataforma!")\nend)',question:'¿Cuándo se intenta imprimir el mensaje?',options:['Cuando algo toca la plataforma','Solo al iniciar Roblox Studio','Cada veinte segundos'],answer:0,explanation:'Touched ejecuta la función cuando detecta contacto. Ojo: también pueden tocarla objetos distintos del jugador.',task:'Haz que una plataforma anuncie en Output cuándo algo la toca. Intenta explicar para qué sirve cada línea.',hints:['Inserta un Script dentro de una Part.','Necesitas el evento Touched.','La estructura es plataforma.Touched:Connect(function(...) ... end).'],reflection:'¿Qué otra acción te gustaría activar con un contacto?'},
 {id:'w2c',world:'constructor',title:'El botón secreto',sub:'Funciones',time:18,emoji:'🔘',description:'Reutiliza instrucciones agrupándolas en una función.',concept:'Una función es un conjunto de instrucciones con nombre. Se ejecuta cuando la llamas.',code:'local function saludar()\n    print("¡Bienvenido!")\nend\n\nsaludar()',question:'¿Cuántas veces aparece el saludo?',options:['Ninguna','Una','Tres'],answer:1,explanation:'La función se define y luego se llama una sola vez.',task:'Escribe una función anunciarVictoria() y haz que muestre un mensaje. Después llámala dos veces.',hints:['Define una función con local function nombre().','Escribe el print dentro y termina con end.','Llama a la función escribiendo su nombre y ().'],reflection:'¿Qué instrucciones repetirías muchas veces en tu juego?'},
 {id:'w3a',world:'inventor',title:'Monedas que cuentan',sub:'Eventos + variables',time:20,emoji:'🪙',description:'Combina lo que sabes para idear una mecánica de recolección.',concept:'Los juegos reales mezclan variables, condiciones y eventos. Antes de escribir código conviene describir paso a paso qué debería ocurrir.',code:'-- Diseño en lenguaje natural:\n-- 1. Detectar quién tocó la moneda\n-- 2. Evitar contarla dos veces\n-- 3. Sumar una moneda\n-- 4. Ocultar o retirar la moneda',question:'¿Por qué necesitamos evitar que una moneda se cuente dos veces?',options:['Para que no se sumen puntos extra al tocarla varias veces','Para que sea más brillante','Porque Luau no permite sumar'],answer:0,explanation:'Touched puede activarse varias veces. Controlar el estado de la moneda evita sumar puntos indebidamente.',task:'Diseña sobre papel o en un documento el comportamiento de una moneda. Divide el problema en cuatro instrucciones y prueba una parte en Studio.',hints:['Primero detecta el contacto.','Piensa en una variable como recogida = false.','Cuando ya se recogió, ignora nuevos contactos.'],reflection:'¿Qué fue más difícil: imaginar la mecánica o dividirla en pasos?'},
 {id:'w3b',world:'inventor',title:'Cazador de errores',sub:'Depuración',time:20,emoji:'🐛',description:'Aprende a encontrar la causa de un fallo sin pedir a la IA que reescriba tu código.',concept:'Depurar implica observar el comportamiento, leer Output, formular una hipótesis, cambiar una cosa y probar otra vez.',code:'local monedas = 4\nif monedas > 5 then\n    print("Premio desbloqueado")\nend',question:'Esperabas un premio con 5 monedas. ¿Cuál es el problema?',options:['Debería ser >= 5','Falta cambiar print por wait','La variable no puede ser local'],answer:0,explanation:'Con > 5 se necesitan al menos 6 monedas. Para incluir el 5 se usa >= 5. Además, el valor de prueba actual es 4.',task:'Haz que el programa muestre el premio al llegar exactamente a 5 monedas. Cambia una cosa cada vez y comprueba Output.',hints:['Prueba el valor 5 y observa qué sucede.','Compara > y >=.','El símbolo >= significa mayor o igual.'],reflection:'¿Qué hipótesis probaste antes de corregirlo?'},
 {id:'w3c',world:'inventor',title:'Tu primera creación',sub:'Diseño de videojuegos',time:25,emoji:'🏆',description:'Prepara una pequeña mecánica original y pruébala en Roblox Studio.',concept:'Un prototipo es una versión sencilla para comprobar si una idea funciona. No necesita tener muchos niveles ni gráficos perfectos.',code:'-- Mi idea:\n-- Objetivo del jugador:\n-- Acción principal:\n-- ¿Cómo se gana?:\n-- ¿Qué probaré primero?:',question:'¿Cuál es la mejor primera versión de una idea grande?',options:['Una mecánica pequeña y comprobable','Un juego enorme sin pruebas','Copiar entero otro videojuego'],answer:0,explanation:'Primero se construye algo pequeño que puedas probar, comprender y mejorar.',task:'Elige una idea (un portal, un coleccionable o una plataforma especial). Describe el objetivo, constrúyela en Studio y pide a otra persona que la pruebe.',hints:['Elige UNA sola mecánica.','Divídela en objetos, reglas y pruebas.','Prueba primero que el comportamiento funciona; después mejora los gráficos.'],reflection:'¿Qué cambiarías después de ver a alguien probar tu juego?'}
];
const M_BY_ID=Object.fromEntries(MISSIONS.map(m=>[m.id,m]));

/* Mini-laboratorio: revisión orientativa mediante patrones, sin ejecutar Luau. */
const CODE_TASKS={
  d2:{label:'Cambia la suma para obtener dos puntos',hint:'Usa puntos = puntos + 2 e imprime el resultado.',checks:[['Actualizas puntos con una suma de 2',/puntos\s*=\s*puntos\s*\+\s*2/],['Muestras el resultado con print',/print\s*\(\s*puntos\s*\)/]]},
  d3:{label:'Haz que una plataforma invisible sea atravesable',hint:'Busca la propiedad que controla las colisiones.',checks:[['Quitas la colisión de la plataforma',/CanCollide\s*=\s*false/]]},
  w1a:{label:'Escribe tu código de monedas desde cero',hint:'Crea monedas con 10; suma 2; muestra monedas.',checks:[['Creas la variable monedas',/local\s+monedas\s*=\s*10/],['Sumas 2 monedas',/monedas\s*=\s*monedas\s*\+\s*2/],['Muestras monedas en Output',/print\s*\(\s*monedas\s*\)/]]},
  w1b:{label:'Crea la condición para abrir la puerta',hint:'Utiliza if monedas >= 5 then y recuerda cerrar el bloque.',checks:[['Compruebas que monedas sea al menos 5',/if\s+monedas\s*>=\s*5\s+then/],['Cierras el bloque condicional',/\bend\b/]]},
  w1c:{label:'Escribe una cuenta atrás de tres a uno',hint:'Utiliza print y task.wait(1) entre cada mensaje.',checks:[['Escribes mensajes para 3, 2 y 1',/print\s*\(\s*["']?3["']?\s*\)[\s\S]*print\s*\(\s*["']?2["']?\s*\)[\s\S]*print\s*\(\s*["']?1["']?\s*\)/],['Incluyes al menos dos esperas',/task\.wait\s*\(\s*1\s*\)[\s\S]*task\.wait\s*\(\s*1\s*\)/]]},
  w2a:{label:'Define una parte semitransparente y atravesable',hint:'Busca Transparency y CanCollide.',checks:[['Defines Transparency a 0.5',/Transparency\s*=\s*0\.5/],['Desactivas CanCollide',/CanCollide\s*=\s*false/]]},
  w2b:{label:'Detecta cuándo tocan una plataforma',hint:'Usa el evento Touched conectado a una función.',checks:[['Escuchas el evento Touched',/\.Touched\s*:\s*Connect\s*\(/],['Defines una función',/function\s*\(/],['Muestras un mensaje',/print\s*\(/]]},
  w2c:{label:'Crea una función de victoria y llámala dos veces',hint:'Necesitas local function anunciarVictoria() y luego dos llamadas.',checks:[['Defines anunciarVictoria',/local\s+function\s+anunciarVictoria\s*\(/],['Muestras un mensaje',/print\s*\(/],['Llamas la función dos veces',/anunciarVictoria\s*\([\s\S]*?\)[\s\S]*anunciarVictoria\s*\([\s\S]*?\)/]]},
  w3b:{label:'Corrige el límite del premio y prueba con cinco monedas',hint:'Cambia > por >= y prueba con exactamente cinco monedas.',checks:[['Pruebas con cinco monedas',/monedas\s*=\s*5/],['La condición incluye el número cinco',/if\s+monedas\s*>=\s*5\s+then/]]}
};
function getChecks(p,id){
 const def=CODE_TASKS[id],code=(p.codeDrafts&&p.codeDrafts[id])||'';
 if(!def)return null;
 const lines=code.split('\n').filter(x=>!(/^\s*--/.test(x))).join('\n');
 return {rules:def.checks.map(([description,re],index)=>({description,met:id==='w2c'&&index===2?(lines.match(/^\s*anunciarVictoria\s*\(\s*\)\s*;?\s*$/gm)||[]).length>=2:re.test(lines)})),hasCode:!!code.trim()};
}
function codeWorkshop(p,m){
 const item=CODE_TASKS[m.id];
 if(!item)return '';
 const review=p.codeReviews[m.id];
 return '<div class="task-panel"><span class="eyebrow">04 · LABORATORIO DE CÓDIGO · OPCIONAL</span>'+
 '<h3>⌨️ Escribe tu propia solución</h3>'+
 '<p>'+esc(item.label)+'. No necesitas copiar el ejemplo. Tu borrador se guarda en este dispositivo.</p>'+
 '<label class="note-label" for="code-draft">Mi código Luau</label>'+
 '<textarea class="textarea code-editor" spellcheck="false" id="code-draft" data-code-draft="'+m.id+'" placeholder="-- Empieza a escribir aquí.&#10;-- Prueba después en Roblox Studio.">'+esc(p.codeDrafts[m.id]||'')+'</textarea>'+
 '<div class="button-row">'+uiBtn('🔎 Revisar mi intento','review-code',m.id,'btn-quiet btn-sm')+'</div>'+
 (review?'<div class="feedback" role="status"><strong>Lista de comprobación (orientativa)</strong><ul>'+review.rules.map(r=>'<li>'+(r.met?'✅ ':'⬜ ')+esc(r.description)+'</li>').join('')+'</ul><p>'+esc(review.message)+'</p></div>':'')+
 '<p class="subtle">Esta revisión solo busca patrones de escritura. <b>No ejecuta Luau, no verifica que el código funcione y no sustituye las pruebas de Roblox Studio.</b></p></div>';
}
function debugWorkshop(p,m){
 if(m.world==='diagnostico')return '';
 const data=p.debugNotes[m.id]||{};
 return '<div class="task-panel"><span class="eyebrow">05 · APRENDE A PEDIR AYUDA</span><h3>🕵️ Tu cuaderno de errores</h3>'+
 '<p>Antes de pedir a la IA que lo arregle, describe el problema con tus palabras. No incluyas información personal.</p>'+
 [['expected','¿Qué querías que ocurriera?'],['actual','¿Qué ocurrió realmente?'],['tried','¿Qué comprobaste o cambiaste?']].map(([field,label],i)=>'<label class="note-label" for="debug-'+i+'">'+esc(label)+'</label><textarea id="debug-'+i+'" class="textarea debug-field" rows="2" data-debug="'+m.id+'" data-field="'+field+'" placeholder="Escribe lo que observaste...">'+esc(data[field]||'')+'</textarea>').join('')+
 '<div class="button-row">'+uiBtn('📋 Preparar mi pregunta para el tutor','copy-question',m.id,'btn-quiet btn-sm')+'</div>'+
 '<p class="subtle">Comparte la pregunta con una persona adulta. La IA debería darte pistas y explicaciones, no sustituir tu trabajo.</p></div>';
}
function questionForTutor(p,m){
 const d=p.debugNotes[m.id]||{};
 return 'Estoy aprendiendo Luau en Roblox Studio. Misión: '+m.title+
 '\nLo que esperaba: '+(d.expected||'(pendiente)')+
 '\nLo que ocurrió: '+(d.actual||'(pendiente)')+
 '\nLo que ya probé: '+(d.tried||'(pendiente)')+
 '\nPor favor, actúa como profesor: hazme preguntas y ofrece UNA pista cada vez. NO escribas la solución ni el código completo. Ayúdame a descubrir el error por mí mismo.';
}

let model=load();
let route={page:'home',world:null,mission:null,modal:false,toast:''};
const app=document.getElementById('app');
function load(){try{const raw=JSON.parse(localStorage.getItem(STORAGE));if(raw&&Array.isArray(raw.profiles))return raw}catch(e){}return{profiles:[],active:null}}
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(model))}catch(e){console.warn('No se pudo guardar el progreso',e)}}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function current(){const p=model.profiles.find(p=>p.id===model.active)||null;if(p){p.codeDrafts ||= {};p.codeReviews ||= {};p.debugNotes ||= {};p.notes ||= {};p.completed ||= {};p.selected ||= {};p.attempts ||= {};p.hints ||= {};p.practiced ||= {}; }return p}
function done(p,id){return !!(p&&p.completed&&p.completed[id])}
function doneN(p,ids){return ids.filter(id=>done(p,id)).length}
function worldUnlocked(p,w){const n=WORLDS.findIndex(x=>x.id===w);return n<=0||doneN(p,WORLDS[n-1].lessons)>=2}
function labelLevel(p){return p.xp>=600?'Maestro de misiones':p.xp>=300?'Inventor en prácticas':p.xp>=120?'Constructor en prácticas':'Explorador'}
function achievement(p){const a=[];if(doneN(p,['d1','d2','d3'])===3)a.push(['🎯','Detective inicial']);if(doneN(p,WORLDS[0].lessons)===3)a.push(['⚡','La chispa']);if(doneN(p,WORLDS[1].lessons)===3)a.push(['🏗️','Constructor']);if(doneN(p,WORLDS[2].lessons)===3)a.push(['🚀','Inventor']);if(Object.keys(p.completed).length>=1)a.push(['🏅','Primer paso']);return a}
function tileStatus(p,id){return done(p,id)?'✅ Completada':'▶ Empezar misión'}
function nav(id){route.page=id;route.mission=null;route.world=null;route.modal=false;route.toast='';render();window.scrollTo(0,0)}
function uiBtn(label,action,arg,cls,disabled){return '<button type="button" class="btn '+(cls||'btn-primary')+'" data-action="'+action+'"'+(arg?' data-id="'+esc(arg)+'"':'')+(disabled?' disabled':'')+'>'+label+'</button>'}
function progress(n,total){return '<div class="progress-bg" role="progressbar" aria-label="Progreso" aria-valuemin="0" aria-valuemax="'+total+'" aria-valuenow="'+n+'"><div class="progress-fill" style="width:'+(n/total*100||0)+'%"></div></div>'}
function stats(p){return '<div class="stats">'+
 '<div class="stat"><span class="stat-icon">⚡</span><div><div class="stat-label">Experiencia</div><strong>'+p.xp+' XP</strong></div></div>'+
 '<div class="stat"><span class="stat-icon">🎯</span><div><div class="stat-label">Misiones</div><strong>'+Object.keys(p.completed).length+' / 12</strong></div></div>'+
 '<div class="stat"><span class="stat-icon">🏅</span><div><div class="stat-label">Insignias</div><strong>'+achievement(p).length+'</strong></div></div></div>'}
function worldCard(p,w){const n=doneN(p,w.lessons),unlocked=worldUnlocked(p,w);return '<article class="world">'+
 '<div class="world-banner" style="--tone:'+w.color+'"><span class="world-emoji">'+w.emoji+'</span><span class="world-label">'+(unlocked?'MUNDO DESBLOQUEADO':'🔒 POR DESBLOQUEAR')+'</span></div>'+
 '<div class="world-body"><div class="eyebrow">'+w.level+'</div><h3>'+esc(w.title)+'</h3><p>'+esc(w.subtitle)+'</p>'+progress(n,3)+
 '<div class="world-footer"><span>'+n+' de 3 misiones</span>'+uiBtn(unlocked?'Explorar →':'Bloqueado','world',w.id,'btn-quiet btn-sm',!unlocked)+'</div></div></article>'}
function home(p){const d=doneN(p,['d1','d2','d3']);const next=MISSIONS.find(m=>m.world==='diagnostico'&&!done(p,m.id))||MISSIONS.find(m=>m.world!=='diagnostico'&&worldUnlocked(p,m.world)&&!done(p,m.id));return '<section class="hero"><div class="hero-copy"><span class="eyebrow">TU AVENTURA COMIENZA AQUÍ</span><h1>Imagina. Programa.<br><span>Hazlo realidad.</span></h1><p>Aprende a crear videojuegos en Roblox Studio. Aquí escribes tú el código: el tutor te guía con pistas, no hace el trabajo por ti.</p><div class="button-row">'+uiBtn('🚀 '+(next?'Continuar aventura':'Ver mis logros'),'mission',next?next.id:'','btn-primary',!next)+uiBtn('🗺️ Ver mundos','nav','map','btn-secondary')+'</div></div><span class="mascot" aria-hidden="true">👾</span><span class="float-tag">+ CREA TU MUNDO ✨</span></section>'+
 stats(p)+'<div class="card assessment"><div><span class="eyebrow">MISIÓN ESPECIAL · 30 MIN</span><h3>🎮 El despertar del programador</h3><p>Una evaluación inicial en forma de aventura: construir un puente, descifrar código y detectar un error. Sin notas ni presión. Puedes hacerla con una persona adulta.</p><div class="button-row">'+uiBtn(d===3?'Revisar evaluación →':d?'Continuar evaluación →':'Comenzar evaluación →','assessment','','btn-secondary')+'</div></div><span class="assessment-badge">🏁</span></div>'+
 '<div class="section-top"><div><h2>Elige tu próximo mundo</h2><p>Misiones cortas que van creciendo contigo.</p></div></div><div class="world-list">'+WORLDS.map(w=>worldCard(p,w)).join('')+'</div>'}
function mapView(p){return '<div class="section-top"><div><span class="eyebrow">TU CAMINO</span><h2>Mapa de mundos 🗺️</h2><p>Supera dos misiones de cada mundo para abrir el siguiente.</p></div></div><div class="world-list">'+WORLDS.map(w=>worldCard(p,w)).join('')+'</div><div class="parent-notice" style="margin-top:24px">💡 No hay límite de tiempo ni obligación de jugar todos los días. Los errores también forman parte de aprender.</div>'}
function assessmentView(p){return '<button class="back-link" data-action="nav" data-id="home">← Volver al inicio</button><div class="level-banner"><div><span class="eyebrow">MISIÓN CERO · EVALUACIÓN INICIAL</span><strong>🏁 El despertar del programador</strong><p>Tres retos de unos 8 minutos y una conversación final. No es un examen.</p></div><span style="font-size:43px">🧭</span></div>'+
 '<div class="section-top"><div><h2>Tres desafíos</h2><p>La persona adulta puede observar y anotar lo que sucede.</p></div></div><div class="lessons">'+MISSIONS.filter(m=>m.world==='diagnostico').map((m,i)=>lessonTile(p,m,i,true)).join('')+'</div><div class="parent-notice" style="margin-top:22px"><b>Para las familias:</b> prepara Roblox Studio en un ordenador. No es necesario saber programar. Al acabar, ve a «Zona familias» y copia el informe para compartirlo con tu tutor.</div>'}
function lessonTile(p,m,i,unlocked){const completed=done(p,m.id);return '<article class="lesson-tile '+(completed?'completed ': '')+(!unlocked?'locked':'')+'">'+
 '<span class="lesson-num">MISIÓN '+String(i+1).padStart(2,'0')+' · '+m.time+' MIN</span><span class="lesson-status">'+(completed?'✅':!unlocked?'🔒':'⭐')+'</span><h3>'+esc(m.emoji+' '+m.title)+'</h3><p>'+esc(m.sub)+'</p>'+uiBtn(completed?'Revisar misión →':unlocked?'Abrir misión →':'Bloqueada','mission',m.id,'btn-quiet btn-sm',!unlocked)+'</article>'}
function worldView(p,w){if(!w)return mapView(p);if(!worldUnlocked(p,w.id))return '<div class="empty"><h2>🔒 Este mundo aún está cerrado</h2><p>Supera al menos dos misiones del mundo anterior.</p>'+uiBtn('Volver al mapa','nav','map','btn-primary')+'</div>';return '<button class="back-link" data-action="nav" data-id="map">← Mapa de mundos</button><div class="level-banner"><div><span class="eyebrow">'+w.level.toUpperCase()+'</span><strong>'+w.emoji+' '+esc(w.title)+'</strong><p>'+esc(w.subtitle)+'</p></div><div style="min-width:130px">'+progress(doneN(p,w.lessons),3)+'</div></div><div class="section-top"><div><h2>Misiones disponibles</h2><p>Puedes repetir cualquier actividad para practicar.</p></div></div><div class="lessons">'+w.lessons.map((id,i)=>lessonTile(p,M_BY_ID[id],i,true)).join('')+'</div>'}
function feedback(p,m){const chosen=p.selected[m.id];if(chosen===undefined)return '';const okay=chosen===m.answer;return '<div class="feedback '+(okay?'':'error')+'" role="status"><b>'+(okay?'✅ ¡Bien razonado!':'🔎 Aún no. Investiga un poco más.')+'</b><p style="margin:5px 0 0">'+(okay?esc(m.explanation):'Prueba otra opción o abre una pista. Equivocarse sirve para descubrir qué falta entender.')+'</p></div>'}
function missionView(p,m){if(!m)return home(p);if(m.world!=='diagnostico'&&!worldUnlocked(p,m.world))return mapView(p);const diag=m.world==='diagnostico',selected=p.selected[m.id],correct=selected===m.answer,h=p.hints[m.id]||0,practiced=!!p.practiced[m.id],completed=done(p,m.id);return '<div class="mission-layout"><section class="card mission-card">'+
 '<button class="back-link" data-action="'+(diag?'assessment':'world')+'" data-id="'+(diag?'':m.world)+'">← Volver a las misiones</button><span class="eyebrow">'+(diag?'EVALUACIÓN INICIAL':'APRENDE LUAU · ROBLOX')+' · '+m.time+' MIN</span><h1>'+m.emoji+' '+esc(m.title)+'</h1><p class="mission-description">'+esc(m.description)+'</p>'+
 '<div class="task-panel"><span class="eyebrow">01 · DESCUBRE</span><h3>Lo que necesitas saber</h3><p>'+esc(m.concept)+'</p>'+(m.code?'<pre class="codeblock"><code>'+esc(m.code)+'</code></pre>'+uiBtn('📋 Copiar ejemplo','copy',m.id,'btn-quiet btn-sm'):'')+'</div>'+
 '<div class="task-panel"><span class="eyebrow">02 · PIENSA</span><div class="question">'+esc(m.question)+'</div><div class="options">'+m.options.map((o,i)=>'<button type="button" class="option '+(selected===i?(correct?'selected':'wrong'):'')+'" data-action="choose" data-id="'+m.id+'" data-index="'+i+'"'+(completed?' disabled':'')+'><span class="option-index">'+String.fromCharCode(65+i)+'</span>'+esc(o)+'</button>').join('')+'</div>'+feedback(p,m)+'</div>'+
 '<div class="task-panel"><span class="eyebrow">03 · CONSTRUYE TÚ</span><h3>Reto en Roblox Studio</h3><p>'+esc(m.task)+'</p><label style="display:flex;gap:10px;align-items:center;cursor:pointer;margin-top:12px"><input type="checkbox" data-practiced="'+m.id+'" '+(practiced?'checked':'')+' '+(completed?'disabled':'')+'><span class="subtle" style="color:#deebff">He intentado la parte práctica en Roblox Studio</span></label><label class="note-label" for="note">Tu diario de explorador (opcional)</label><textarea class="textarea" id="note" data-note="'+m.id+'" placeholder="'+esc(m.reflection)+'" '+(completed?'readonly':'')+'>'+esc(p.notes[m.id]||'')+'</textarea></div>'+
 codeWorkshop(p,m)+debugWorkshop(p,m)+
 '<div class="button-row">'+(completed?'<div class="feedback">🏆 ¡Misión registrada! Ganaste '+p.completed[m.id].xp+' XP. Puedes volver a leerla cuando quieras.</div>':uiBtn(diag?'✅ Registrar intento':'🏆 Completar misión','finish',m.id,'btn-primary',!diag&&!correct))+
 (completed?uiBtn('Siguiente desafío →','next',m.id,'btn-secondary'):'')+'</div>'+
 '</section><aside class="sticky-panel"><div class="helper-panel"><h3>🤖 Tu tutor de pistas</h3><p>Antes de pedir una pista, intenta explicarte qué sabes, qué esperabas y qué ha ocurrido.</p><div class="chip">Pistas '+h+' / 3</div><div class="hint-box"><h3>💡 Pista '+(h||'disponible')+'</h3><p>'+(h?esc(m.hints[h-1]):'¿Te has atascado? Puedes desbloquear pistas una a una. No hay penalización.')+'</p>'+uiBtn(h>=3?'Todas las pistas abiertas':'Ver '+(h?'otra':'primera')+' pista','hint',m.id,'btn-quiet btn-sm',h>=3)+'</div></div><div class="helper-panel"><h3>🧩 Regla de oro</h3><p>La IA es tu profesora, no tu programadora. <b>Tú escribes el código.</b></p><ul><li>¿Qué debería pasar?</li><li>¿Qué pasó de verdad?</li><li>¿Qué cambio pequeño probarás?</li></ul><a class="btn btn-quiet btn-sm" href="https://create.roblox.com/" target="_blank" rel="noopener noreferrer">Abrir Roblox Studio ↗</a></div></aside></div>'}
function progressView(p){const badges=achievement(p),entries=Object.entries(p.completed).sort((a,b)=>b[1].date.localeCompare(a[1].date));return '<div class="section-top"><div><span class="eyebrow">TU AVENTURA</span><h2>Mi progreso 📈</h2><p>No competimos con otros: descubrimos cuánto has aprendido.</p></div></div>'+stats(p)+'<div class="level-banner"><div><span class="eyebrow">NIVEL ACTUAL</span><strong>🌟 '+labelLevel(p)+'</strong><p>La experiencia se obtiene al intentarlo, razonar y practicar.</p></div><span style="font-size:45px">🏆</span></div><div class="summary-grid"><section class="card"><h3>🏅 Insignias</h3>'+(badges.length?'<div class="badge-row">'+badges.map(x=>'<span class="badge-award"><span>'+x[0]+'</span>'+x[1]+'</span>').join('')+'</div>':'<p class="view-lead">Tu primera insignia aparecerá después de completar una misión.</p>')+'</section><section class="card"><h3>📚 Recorrido</h3>'+WORLDS.map(w=>'<p class="subtle">'+esc(w.title)+' · '+doneN(p,w.lessons)+'/3</p>'+progress(doneN(p,w.lessons),3)).join('')+'</section></div><section class="card" style="margin-top:20px"><h3>🗓️ Misiones realizadas</h3>'+(entries.length?'<div class="timeline">'+entries.map(([id,v])=>'<div class="timeline-item"><div><strong>'+esc(M_BY_ID[id]?M_BY_ID[id].emoji+' '+M_BY_ID[id].title:id)+'</strong><small>'+new Date(v.date).toLocaleDateString('es-ES')+'</small></div><b style="color:var(--mint)">+'+v.xp+' XP</b></div>').join('')+'</div>':'<div class="empty"><p>Aún no has registrado una misión.</p></div>')+'</section>'}
function report(p){const items=Object.entries(p.completed).sort((a,b)=>a[1].date.localeCompare(b[1].date));let rows=['CODEQUEST · INFORME DE APRENDIZAJE','Alias: '+p.name,'Nivel: '+labelLevel(p),'Experiencia: '+p.xp+' XP','Misiones completadas: '+items.length,'Fecha del informe: '+new Date().toLocaleDateString('es-ES'),'','Importante: este informe recoge respuestas y declaraciones, no comprueba lo realizado en Roblox Studio.',''];for(const [id,v] of items){const m=M_BY_ID[id];if(!m)continue;rows.push('MISIÓN: '+m.title,'Fecha: '+new Date(v.date).toLocaleDateString('es-ES'),'Respuesta final correcta: '+(v.correct?'Sí':'No o no respondida'),'Intentos de respuesta: '+v.attempts,'Pistas utilizadas: '+(p.hints[id]||0),'Práctica en Roblox declarada: '+(v.practiced?'Sí':'No'),'XP: '+v.xp,'Observaciones: '+(v.note||'Sin anotaciones'),'Código escrito (no verificado):\n'+((p.codeDrafts||{})[id]||'No hay borrador'),'Cuaderno de errores: '+JSON.stringify((p.debugNotes||{})[id]||{}),'');}if(!items.length)rows.push('No se han registrado misiones todavía.');rows.push('No hay evaluación automática de habilidades prácticas ni ejecución de código.');return rows.join('\n')}

/* Copias locales: validación estricta y sin transferencia a servidores. */
function backupText(){return JSON.stringify({app:'CodeQuest',version:1,exportedAt:new Date().toISOString(),profiles:model.profiles,active:model.active},null,2)}
function readBackup(source){
 if(!source||source.app!=='CodeQuest'||source.version!==1||!Array.isArray(source.profiles)||source.profiles.length>5||source.profiles.length<1)throw Error('El archivo no es una copia válida de CodeQuest.');
 function boundedNum(v,min,max){const n=Number(v);return Number.isFinite(n)?Math.min(max,Math.max(min,Math.trunc(n))):min}
 function safeText(s,max){return typeof s==='string'?s.slice(0,max):''}
 function onlyIds(raw,convert){const out=Object.create(null);if(raw&&typeof raw==='object'&&!Array.isArray(raw)){for(const m of MISSIONS){if(Object.prototype.hasOwnProperty.call(raw,m.id))out[m.id]=convert(raw[m.id],m.id)}}return out}
 const ids=new Set(),profiles=source.profiles.map((old,index)=>{
   if(!old||typeof old!=='object'||Array.isArray(old))throw Error('Se ha detectado un perfil no válido.');
   const name=safeText(old.name,22).trim();
   if(name.length<2)throw Error('Hay un perfil sin apodo válido.');
   const id='restored_'+index;
   if(ids.has(id))throw Error('Hay perfiles duplicados.');ids.add(id);
   const completed=onlyIds(old.completed,(entry)=>{
      if(!entry||typeof entry!=='object')return null;
      const date=safeText(entry.date,35);
      const validDate=!Number.isNaN(Date.parse(date));
      if(!validDate)return null;
      return {date,xp:boundedNum(entry.xp,0,60),correct:entry.correct===true,practiced:entry.practiced===true,attempts:boundedNum(entry.attempts,0,999),note:safeText(entry.note,1500)}
   });
   for(const key of Object.keys(completed)){if(!completed[key])delete completed[key]}
   const selected=onlyIds(old.selected,v=>boundedNum(v,0,2));
   const attempts=onlyIds(old.attempts,v=>boundedNum(v,0,999));
   const hints=onlyIds(old.hints,v=>boundedNum(v,0,3));
   const notes=onlyIds(old.notes,v=>safeText(v,1500));
   const practiced=onlyIds(old.practiced,v=>v===true);
   const codeDrafts=onlyIds(old.codeDrafts,v=>safeText(v,5000));
   const debugNotes=onlyIds(old.debugNotes,v=>({expected:safeText(v&&v.expected,900),actual:safeText(v&&v.actual,900),tried:safeText(v&&v.tried,900)}));
   const xp=Object.values(completed).reduce((sum,item)=>sum+item.xp,0);
   return{id,name,xp,completed,selected,attempts,hints,notes,practiced,codeDrafts,codeReviews:{},debugNotes};
 });
 const activeIndex=source.profiles.findIndex(p=>p&&p.id===source.active);
 return {profiles,active:profiles[Math.max(0,activeIndex)].id};
}
function downloadFile(name,content,type){
 const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);
}

function parentsView(p){return '<div class="section-top"><div><span class="eyebrow">ACOMPAÑAMIENTO FAMILIAR</span><h2>Zona familias 👨‍👩‍👧‍👦</h2><p>Para observar sin convertir el aprendizaje en un examen.</p></div></div><div class="parent-notice">🔐 <b>Privacidad:</b> versión de prueba sin cuentas ni base de datos. El alias y el progreso se guardan solamente en este navegador. Si se borran sus datos o se cambia de dispositivo, el progreso no se recupera. No introduzcáis apellidos ni información sensible.</div><div class="summary-grid"><section class="card"><h3>🧭 ¿Qué conviene observar?</h3><p class="view-lead">Si comprende el código, si formula hipótesis, cómo reacciona ante errores y si puede explicar lo que ha construido. Las pistas no son un fracaso: ayudan a aprender.</p><p class="view-lead">La evaluación inicial se puede completar aunque no acierte todas las preguntas, para detectar su punto de partida.</p></section><section class="card"><h3>🛡️ Sobre el tutor</h3><p class="view-lead">Esta versión utiliza <b>pistas pedagógicas escritas y revisables</b>. Todavía no conecta con un modelo de IA ni permite conversaciones abiertas con menores. La futura integración necesitará controles de seguridad y supervisión.</p></section></div><section class="card" style="margin-top:18px"><h3>📋 Informe para compartir</h3><p class="view-lead">Puedes copiar el informe y compartirlo con ChatGPT desde una conversación gestionada por una persona adulta para revisar el aprendizaje y adaptar las próximas misiones.</p><textarea class="textarea" style="min-height:280px" readonly id="parent-report">'+esc(report(p))+'</textarea><div class="button-row">'+uiBtn('📋 Copiar informe','copy-report','','btn-primary')+uiBtn('⬇ Descargar informe','download-report','','btn-quiet')+'</div></section><section class="card" style="margin-top:20px"><h3>💾 Guardar o recuperar el progreso</h3><p class="view-lead">Descarga un archivo privado con los perfiles y las actividades de este navegador. Guárdalo en un lugar seguro: contiene apodos, respuestas y borradores de código. Para recuperar una copia, tendrás que elegir el archivo desde este dispositivo. <b>Importar reemplaza todos los perfiles locales actuales.</b></p><div class="button-row">'+uiBtn('⬇ Guardar copia de seguridad','download-backup','','btn-primary')+uiBtn('↥ Recuperar una copia','open-backup','','btn-quiet')+'</div><input id="backup-input" class="sr-only" type="file" accept=".json,application/json" aria-label="Seleccionar copia de CodeQuest" data-backup-input></section>'}
function header(p){const navLinks=[['home','🏠','Inicio'],['map','🗺️','Mundos'],['progress','🏆','Progreso'],['parents','👨‍👩‍👧','Familias']];return '<div class="layout"><aside class="sidebar"><div class="logo"><span class="logo-mark">⚡</span><span>Code<em>Quest</em></span></div><nav class="nav-group" aria-label="Principal">'+navLinks.map(x=>'<button type="button" class="nav-item '+(route.page===x[0]?'active':'')+'" data-action="nav" data-id="'+x[0]+'"><span class="nav-ico">'+x[1]+'</span><span>'+x[2]+'</span></button>').join('')+'</nav><div class="side-bottom"><span class="mini">TU MISIÓN</span><strong>Aprender creando</strong><p>Piensa. Prueba. Equivócate. Descubre. Vuelve a intentar.</p></div></aside><div class="main-area"><header class="topbar"><div class="crumb">ACADEMIA DE CREADORES <span style="color:var(--mint)">✦</span></div><div class="top-actions"><span class="pill">⚡ <b>'+p.xp+' XP</b></span><button class="profile-switch" type="button" data-action="profiles" aria-label="Cambiar perfil">👾 '+esc(p.name)+' ▾</button></div></header><main class="content">'}
function bottom(){return '<footer class="footer">CodeQuest · Aprende con curiosidad, a tu propio ritmo · <a href="https://create.roblox.com/docs" target="_blank" rel="noopener noreferrer">Documentación oficial de Roblox ↗</a></footer></main></div></div>'}
function profileModal(){return '<div class="modal-screen" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal"><div class="celebrate">👾</div><span class="eyebrow">ACADEMIA DE CREADORES</span><h2 id="modal-title">'+(model.profiles.length?'Elige tu explorador':'¡Bienvenido a CodeQuest!')+'</h2><p>'+(!model.profiles.length?'Vamos a construir tu aventura. Utiliza un apodo (no tu nombre completo); los datos se guardarán solamente en este navegador.':'Elige un perfil o crea otro para empezar desde cero.')+'</p>'+(model.profiles.length?'<div class="profile-list">'+model.profiles.map(p=>'<button type="button" class="profile-option" data-action="select-profile" data-id="'+esc(p.id)+'">👾 '+esc(p.name)+' <span>'+p.xp+' XP →</span></button>').join('')+'</div>':'')+'<form id="add-profile-form"><label class="note-label" for="alias">Apodo del explorador</label><div class="profile-add"><input id="alias" class="input" name="alias" maxlength="22" placeholder="Ej. Capitán Pixel" autocomplete="off" required><button class="btn btn-primary" type="submit">Crear →</button></div></form><p class="subtle" style="font-size:12px;margin-top:20px">Recomendado con acompañamiento familiar. No se necesita correo, contraseña ni datos personales.</p>'+(model.profiles.length?uiBtn('Cancelar','close-modal','','btn-quiet btn-sm'):'')+'</div></div>'}
function render(){const p=current();if(!p){app.innerHTML=profileModal();return}let body='';if(route.page==='home')body=home(p);else if(route.page==='map')body=mapView(p);else if(route.page==='assessment')body=assessmentView(p);else if(route.page==='world')body=worldView(p,WORLDS.find(w=>w.id===route.world));else if(route.page==='mission')body=missionView(p,M_BY_ID[route.mission]);else if(route.page==='progress')body=progressView(p);else if(route.page==='parents')body=parentsView(p);else body=home(p);app.innerHTML=header(p)+body+(route.toast?'<div class="feedback" role="status" style="margin-top:22px">'+esc(route.toast)+'</div>':'')+bottom()+(route.modal?profileModal():'')}
function openMission(id){if(!M_BY_ID[id])return;route.page='mission';route.mission=id;route.modal=false;route.toast='';render();window.scrollTo(0,0)}
function nextMission(id){const all=MISSIONS,ix=all.findIndex(m=>m.id===id);const next=all[ix+1];if(next&&((next.world==='diagnostico')||worldUnlocked(current(),next.world)))openMission(next.id);else nav('progress')}
function copyText(value){if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(value).then(()=>{route.toast='✅ Copiado al portapapeles';render()}).catch(()=>{route.toast='No se pudo copiar automáticamente. Selecciona el texto y cópialo manualmente.';render()})}else{route.toast='Selecciona y copia el texto manualmente.';render()}}
document.addEventListener('submit',ev=>{if(ev.target.id!=='add-profile-form')return;ev.preventDefault();const name=(new FormData(ev.target).get('alias')||'').toString().trim().slice(0,22);if(name.length<2){alert('Escribe un apodo de al menos dos caracteres');return}if(model.profiles.length>=5){alert('En este dispositivo se permiten hasta cinco perfiles.');return}const id='p_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6);model.profiles.push({id,name,xp:0,completed:{},selected:{},attempts:{},hints:{},notes:{},practiced:{}});model.active=id;persist();route={page:'home',world:null,mission:null,modal:false,toast:''};render()});
document.addEventListener('change',ev=>{const p=current();if(!p)return;const el=ev.target;if(el.dataset.practiced){p.practiced[el.dataset.practiced]=el.checked;persist()}if(el.dataset.note){p.notes[el.dataset.note]=el.value.slice(0,1500);persist()}});
document.addEventListener('input',ev=>{const p=current();if(!p)return;const el=ev.target;if(el.dataset.note){p.notes[el.dataset.note]=el.value.slice(0,1500);persist()}if(el.dataset.codeDraft){p.codeDrafts[el.dataset.codeDraft]=el.value.slice(0,5000);delete p.codeReviews[el.dataset.codeDraft];persist()}if(el.dataset.debug){const id=el.dataset.debug,field=el.dataset.field;if(['expected','actual','tried'].includes(field)){p.debugNotes[id] ||= {};p.debugNotes[id][field]=el.value.slice(0,900);persist()}}});
document.addEventListener('click',ev=>{const el=ev.target.closest('[data-action]');if(!el)return;const action=el.dataset.action,id=el.dataset.id,p=current();if(action==='profiles'){route.modal=true;render();return}if(action==='close-modal'){route.modal=false;render();return}if(action==='select-profile'){model.active=id;persist();route={page:'home',world:null,mission:null,modal:false,toast:''};render();return}if(!p)return;if(action==='nav'){nav(id);return}if(action==='assessment'){nav('assessment');return}if(action==='world'){route.page='world';route.world=id;route.toast='';render();window.scrollTo(0,0);return}if(action==='mission'){openMission(id);return}if(action==='next'){nextMission(id);return}if(action==='copy'){const m=M_BY_ID[id];if(m)copyText(m.code);return}if(action==='review-code'){const check=getChecks(p,id);if(!check)return;const missing=check.rules.filter(r=>!r.met);p.codeReviews[id]={rules:check.rules,message:!check.hasCode?'Escribe primero tu intento.':missing.length?'Hay '+missing.length+' elemento(s) que revisar. Observa las indicaciones, modifica una cosa y prueba en Studio.':'Has incluido los elementos que buscamos. Ahora prueba el código en Roblox Studio; aquí no podemos asegurar que funcione.'};persist();render();return}if(action==='copy-question'){if(!M_BY_ID[id])return;const d=p.debugNotes[id]||{};if(!d.expected?.trim()||!d.actual?.trim()){route.toast='Escribe al menos qué esperabas y qué ocurrió antes de copiar tu pregunta.';render();return}copyText(questionForTutor(p,M_BY_ID[id]));return}if(action==='download-backup'){downloadFile('CodeQuest-copia-de-seguridad.json',backupText(),'application/json;charset=utf-8');return}if(action==='open-backup'){document.getElementById('backup-input')?.click();return}if(action==='copy-report'){copyText(report(p));return}if(action==='download-report'){const blob=new Blob([report(p)],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='CodeQuest-informe-'+p.id+'.txt';a.click();URL.revokeObjectURL(url);return}
 if(action==='choose'){const m=M_BY_ID[id],i=Number(el.dataset.index);if(!m||done(p,id))return;p.selected[id]=i;p.attempts[id]=(p.attempts[id]||0)+1;persist();render();return}
 if(action==='hint'){const m=M_BY_ID[id];if(m){p.hints[id]=Math.min(3,(p.hints[id]||0)+1);persist();render()}return}
 if(action==='finish'){const m=M_BY_ID[id];if(!m||done(p,id))return;const correct=p.selected[id]===m.answer;if(m.world!=='diagnostico'&&!correct)return;const practiced=!!p.practiced[id];const earned=20+(correct?25:0)+(practiced?15:0);p.completed[id]={date:new Date().toISOString(),xp:earned,correct,practiced,attempts:p.attempts[id]||0,note:p.notes[id]||''};p.xp+=earned;persist();route.toast='🎉 ¡Misión registrada! Has ganado '+earned+' XP. Sigue explorando a tu ritmo.';render();window.scrollTo({top:0,behavior:'smooth'});return}
});

document.addEventListener('change',async ev=>{
 if(!ev.target.matches||!ev.target.matches('[data-backup-input]'))return;
 const file=ev.target.files&&ev.target.files[0];if(!file)return;
 try{
   if(file.size>1048576)throw Error('La copia es demasiado grande (máximo 1 MB).');
   const candidate=readBackup(JSON.parse(await file.text()));
   if(!window.confirm('Esta operación reemplazará TODOS los perfiles y progresos de CodeQuest en este navegador. ¿Quieres continuar?'))return;
   model=candidate;persist();route={page:'parents',world:null,mission:null,modal:false,toast:'✅ Copia restaurada en este navegador.'};render();
 }catch(error){route.toast='No se pudo recuperar la copia: '+error.message;render()}
});

render();
