/* CodeQuest · Ruta Luau 1.0 · datos didácticos. Sin dependencias externas. */
const CURRICULUM_UNITS=[
 {id:'fundamentos',title:'Unidad 1 · Piensa en instrucciones',emoji:'🧠',sub:'Variables y pequeñas operaciones',lessons:['lab1','lab2']},
 {id:'decisiones',title:'Unidad 2 · Haz que ocurran cosas',emoji:'⚙️',sub:'Condiciones y tiempo',lessons:['lab3','lab4']},
 {id:'interacciones',title:'Unidad 3 · Da vida a tu mundo',emoji:'🧩',sub:'Funciones y eventos',lessons:['lab5','lab6']},
 {id:'creador',title:'Unidad 4 · Eres el creador',emoji:'🎮',sub:'Depurar e inventar una mecánica',lessons:['lab7','lab8']}
];
const CURRICULUM_LESSONS=[
 {id:'lab1',unit:'fundamentos',emoji:'💚',title:'La mochila de vidas',time:15,
  objective:'Comprender que una variable guarda un número que puedes cambiar.',
  snippet:'local gemas = 2\ngemas = gemas + 4\nprint(gemas)',
  predict:'Antes de ejecutar el ejemplo, ¿qué crees que aparecerá en Output? ¿Por qué?',
  task:'En Roblox Studio, crea tú un Script con una variable llamada vidas que empiece en 3. Súmale 2 e imprime su valor. Prueba que el resultado sea 5.',
  reflection:'¿Qué comprobaste en Output? ¿Qué cambiaría si sumaras 1 en lugar de 2?',
  hints:['Busca cómo se crea una variable usando local.','Puedes sumar sobre una variable escribiendo su nombre a ambos lados del igual.','Después de actualizar el número, print te ayuda a ver el resultado.'],
  rules:[{title:'Creas una variable llamada vidas con 3',source:'\\blocal\\s+vidas\\s*=\\s*3\\b'}, {title:'Actualizas vidas sumando 2',source:'\\bvidas\\s*=\\s*vidas\\s*\\+\\s*2\\b'}, {title:'Muestras su valor',source:'\\bprint\\s*\\(\\s*vidas\\s*\\)'}]},
 {id:'lab2',unit:'fundamentos',emoji:'🪙',title:'La tienda de monedas',time:15,
  objective:'Entender que una variable también puede disminuir.',
  snippet:'local energia = 8\nenergia = energia - 2\nprint(energia)',
  predict:'¿Qué muestra el ejemplo? ¿Qué pasaría si restaras 5 en vez de 2?',
  task:'Crea en Roblox Studio una variable monedas que empiece con 10, réstale 4 por una compra y muestra el valor final. ¿Cuántas quedan?',
  reflection:'¿Qué pasaría si el jugador gastara más monedas de las que tiene? ¿Cómo podrías evitarlo más adelante?',
  hints:['Empieza creando monedas con valor 10.','Para restar, emplea el símbolo - en una asignación nueva.','print(monedas) sirve para ver el resultado actualizado.'],
  rules:[{title:'Inicializas monedas con 10',source:'\\blocal\\s+monedas\\s*=\\s*10\\b'}, {title:'Restas 4 monedas',source:'\\bmonedas\\s*=\\s*monedas\\s*-\\s*4\\b'}, {title:'Muestras monedas',source:'\\bprint\\s*\\(\\s*monedas\\s*\\)'}]},
 {id:'lab3',unit:'decisiones',emoji:'🚪',title:'La puerta de tres llaves',time:18,
  objective:'Crear una decisión con if, then y end.',
  snippet:'local nivel = 8\nif nivel >= 8 then\n    print("Puedes entrar")\nend',
  predict:'¿Qué ocurriría si nivel fuera 7? ¿Qué línea decide si se muestra el mensaje?',
  task:'Haz tu propio programa: empieza con llaves = 3; muestra «Puerta abierta» solo si llaves es mayor o igual que 3. Prueba después con llaves = 2.',
  reflection:'¿Con qué valor se abre y con cuál no? ¿Qué cambiaste para ponerlo a prueba?',
  hints:['Utiliza una variable llamada llaves.','En la condición compara llaves con 3 usando >=.','Dentro del if escribe print y termina el bloque con end.'],
  rules:[{title:'Guardas tres llaves',source:'\\blocal\\s+llaves\\s*=\\s*3\\b'}, {title:'Compruebas el mínimo de tres llaves',source:'\\bif\\s+llaves\\s*>=\\s*3\\s+then\\b'},{title:'Muestras el mensaje dentro de una condición',source:'\\bprint\\s*\\('},{title:'Cierras el bloque',source:'\\bend\\b'}]},
 {id:'lab4',unit:'decisiones',emoji:'⏳',title:'Cuenta atrás para jugar',time:18,
  objective:'Organizar instrucciones con pausas.',
  snippet:'print("Preparados")\ntask.wait(2)\nprint("¡Ya!")',
  predict:'¿Cuál de los dos mensajes aparece primero? ¿Cuánto tiempo pasa aproximadamente entre ellos?',
  task:'Escribe una cuenta atrás que muestre 3, luego 2 y luego 1, con una pausa de aproximadamente un segundo entre cada número. Después muestra «¡Adelante!».',
  reflection:'¿Qué ocurre si cambias las pausas a 0.5 segundos? ¿Lo has probado?',
  hints:['Empieza con print(3) y luego escribe otro print para el 2.','task.wait recibe la espera aproximada en segundos.','Coloca task.wait(1) entre 3 y 2 y entre 2 y 1.'],
  rules:[{title:'Muestras 3, luego 2 y después 1',source:'print\\s*\\(\\s*["\\x27]?3["\\x27]?\\s*\\)[\\s\\S]*print\\s*\\(\\s*["\\x27]?2["\\x27]?\\s*\\)[\\s\\S]*print\\s*\\(\\s*["\\x27]?1["\\x27]?\\s*\\)'},{title:'Usas al menos dos pausas de un segundo',source:'task\\.wait\\s*\\(\\s*1\\s*\\)',minMatches:2}]},
 {id:'lab5',unit:'interacciones',emoji:'📣',title:'La voz de la victoria',time:18,
  objective:'Definir una función y llamarla cuando quieras.',
  snippet:'local function saludar()\n    print("Hola")\nend\n\nsaludar()',
  predict:'¿Por qué el mensaje no aparece simplemente al definir la función? ¿Cuándo aparece?',
  task:'Crea una función llamada celebrar que muestre «Victoria». Llámala dos veces desde fuera de la función y observa Output.',
  reflection:'¿Qué diferencia hay entre crear una función y ejecutarla? ¿Cuántas veces apareció el mensaje?',
  hints:['Una función se crea con local function nombre().','Coloca print dentro de la función y cierra con end.','Después de end llama a celebrar() dos veces.'],
  rules:[{title:'Defines una función celebrar',source:'\\blocal\\s+function\\s+celebrar\\s*\\(\\s*\\)'},{title:'Usas print dentro de tu programa',source:'\\bprint\\s*\\('},{title:'Llamas a celebrar dos veces',source:'^\\s*celebrar\\s*\\(\\s*\\)\\s*;?\\s*$',flags:'gm',minMatches:2}]},
 {id:'lab6',unit:'interacciones',emoji:'🦶',title:'La plataforma parlante',time:20,
  objective:'Responder a un contacto mediante el evento Touched.',
  snippet:'-- Una Part puede detectar un contacto.\n-- Su evento se llama Touched.',
  predict:'¿Por qué un objeto necesita un evento en vez de mostrar el mensaje una sola vez al iniciar?',
  task:'En Roblox Studio inserta un Script dentro de una Part anclada. Escribe código para que, cuando algo toque la Part, aparezca «Me han tocado» en Output.',
  reflection:'¿Apareció el mensaje una sola vez o varias? ¿Qué otras cosas podrían tocar la plataforma además del jugador?',
  hints:['El Script puede encontrar la Part que lo contiene con script.Parent.','La plataforma tiene el evento Touched y puedes conectarlo mediante :Connect(function(...).','Coloca print dentro de la función que se ejecutará cuando haya contacto.'],
  rules:[{title:'Accedes a la plataforma que contiene el script',source:'\\bscript\\.Parent\\b'},{title:'Conectas el evento Touched',source:'\\.Touched\\s*:\\s*Connect\\s*\\(\\s*function\\s*\\('},{title:'Muestras un mensaje al tocarla',source:'\\bprint\\s*\\('},{title:'Cierras la función del evento',source:'\\bend\\s*\\)'}]},
 {id:'lab7',unit:'creador',emoji:'🐛',title:'La pared con un fallo',time:18,
  objective:'Localizar un error relacionado con visibilidad y colisión.',
  snippet:'local pared = script.Parent\npared.Transparency = 1\npared.CanCollide = true',
  predict:'¿Por qué la pared podría ser invisible y seguir bloqueando al jugador?',
  task:'Crea una pared en Roblox Studio, prueba el código del ejemplo y escribe tú la corrección para que sea invisible y atravesable. Cambia solo lo necesario, ejecuta y comprueba la diferencia.',
  reflection:'¿Cuál era tu hipótesis? ¿Qué línea modificaste? ¿Cómo comprobaste que ya podías atravesarla?',
  hints:['Transparency controla la visibilidad pero no el choque.','CanCollide controla si una parte choca con otras.','Para que sea atravesable, la colisión tiene que estar desactivada.'],
  rules:[{title:'Encuentras la parte que contiene el script',source:'\\bscript\\.Parent\\b'},{title:'La vuelves invisible',source:'\\.Transparency\\s*=\\s*1\\b'},{title:'Desactivas su colisión',source:'\\.CanCollide\\s*=\\s*false\\b'}]},
 {id:'lab8',unit:'creador',emoji:'🌟',title:'Mi primera idea original',time:25,
  objective:'Planificar, probar y explicar una mecánica inventada por ti.',
  snippet:'-- MI IDEA:\n-- ¿Qué hará el jugador?\n-- ¿Qué objetos necesito?\n-- ¿Qué evento o condición hará que algo cambie?\n-- ¿Cómo sabré que funciona?',
  predict:'Antes de empezar, explica en dos o tres frases cuál será la regla especial de tu juego.',
  task:'Elige UNA mecánica pequeña: un suelo que cambia de color, un mensaje secreto al pisar una plataforma o una puerta que se abre con una condición. Escribe tú el código, pruébalo en Studio e identifica un aspecto que mejorarías.',
  reflection:'¿Qué lograste que funcionara? ¿Qué error encontraste? ¿Qué cambiarías si tuvieras diez minutos más?',
  hints:['Elige solo una idea que puedas comprobar en pocos minutos.','Divide el trabajo en objetos, instrucciones, evento y prueba.','Si algo falla, escribe qué esperabas, qué pasó y qué intentarás ahora.'],
  rules:[]}
];
const CURRICULUM_BY_ID=Object.fromEntries(CURRICULUM_LESSONS.map(x=>[x.id,x]));
